import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getBasePath } from "@/utils/basePath";
import Script from "next/script";

const basePath = getBasePath();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vinyl Visualizer",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.VERCEL_URL || "https://bgolski.github.io"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="utf-8" />
        <meta name="base-path" content={basePath} />
        <link rel="icon" href={`${basePath}/favicon.ico`} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* Load helper scripts */}
        <Script
          src="https://html2canvas.hertzen.com/dist/html2canvas.min.js"
          strategy="beforeInteractive"
        />
        <Script src={`${basePath}/path-fixer.js`} strategy="afterInteractive" />
        <Script src={`${basePath}/download-helper.js`} strategy="afterInteractive" />
      </body>
    </html>
  );
}
